[package]
name = "sekshibot"
version = "0.1.0"
authors = ["Renée Kooi <renee@kooi.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
async-std = { version = "1.6.2", features = ["unstable"] }
async-trait = "0.1.36"
async-tungstenite = { version = "0.7.1", features = ["async-std-runtime", "async-tls"] }
bincode = "1.3.1"
chrono = { version = "0.4.13", features = ["serde"] }
femme = "2.1.0"
futures = "0.3.5"
gumdrop = "0.8.0"
log = "0.4.8"
nom = "5.1.2"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"
sled = "0.33.0"
thiserror = "1.0.20"
ureq = { version = "1.3.0", features = ["json"] }

[profile.release]
lto = true
